EnCiv/undebate

README.md, app/api/send-contact-us.js, app/server/util/send-email.js
The configuration steps in the readme file have been vastly elaborated on.  Also, site-feedback will work if email is not setup , putting the feedback into the log.
=> configuration steps

app/models/iota.js
=> bp_info added to iota

.babelrc, app/components/site-feedback.jsx, app/components/web-components/candidate-conversation.jsx, app/components/web-components/undebate.jsx, package-lock.json, package.json
Show a better error message when apple safari doesn't support media recorder.
bable and rgba fix for MS Edge browser
=> Better handle no MediaRecorder on Apple, edge tweaks 

package-lock.json, package.json
log4js-node-mongodb remove (not used)
to updates at level 2
=> resolve npmaudit this day

app/components/web-components/candidate-conversation.jsx, app/components/web-components/undebate.jsx
This is hard to duplicate, but I saw it once.  Now the stall window will clear when the user hits continue (to request permission). This addresses issue #2
=> clear stalled when clearing requestPermission issue #2

app/tools/bpmvp-viewer-recorder.js, app/tools/csv-create-cc-pair.js, app/tools/lacrosse-viewer-recorder.js
now takes a js file as a parameter to describe the template and functions- created larcross-viewer-records as first one - bpmvp-viewer-recorder created from what was there, but not tested.
=> csv-create-cc 

app/components/conversation-header.jsx, app/components/join.jsx, app/components/web-components/undebate.jsx, app/tools/lacrosse-viewer-recorder.js
adds a information button, that links to instructions
updates to the videos for lacrose
join button bigger, turns green when active, input text bigger too
=> Lacrosse updates

app/components/conversation-header.jsx, app/components/join.jsx, app/components/web-components/undebate.jsx, app/tools/lacrosse-viewer-recorder.js
fixed the x in the really close window.
=> Lacrosse updates -again

README.md, app/components/web-components/index.js, app/components/web-components/undebate-iframes.js, doc/# Install.md
demo of rendering a page with 2 viewers in it
explanation of how to add new pages to server
install instructions moved to install.md
=> Iframe demo

package.json
=> npm run-dev-no-inspect in case debug port is taken

app/components/web-components/undebate.jsx
Undebate logo can be none. clicking on instruction link doesn't start video if not started, calcFontSize does not emit error message
=> Instructions don't start video, logo can be none, no calcFontSize message

app/components/react-camera-recorder.jsx, app/components/web-components/undebate.jsx
Lets the user choose the camera when recording, if there is more than one videoinput
=> Camera chooser

app/api/create-participant.js, app/server/events/index.js, app/server/events/notify-of-new-participant.js, app/server/start.js
there is a new server/events directory.  code that wants to generate events should add the event name to server/events/index.js
code that wants to subscribe to events should be in the server/events directory
include serverEvents from  "../server/events" // you have to get the path right
and then
serverEvents.on(serverEvents.eNames.EVENT_NAME, (params)=>{your function})
=> Server events

app/components/lib/socialShareSVG.jsx, app/components/web-components/candidate-conversation.jsx, app/components/web-components/undebate.jsx
The buttons have titles explaining what they do. This was requested by "Bruce". The share button's cursor changes to a pointer.
=> Hover text

app/components/web-components/undebate.jsx
meaning the listening round is the initial round.
=> 0 is a valid listening round

app/components/web-components/candidate-conversation.jsx
Navigates through the offices in an election.
=> chevrons to navigate to nextOffice or previousOffice if the exist.

app/server/server.js, package-lock.json, package.json
added helmet to prevent Cross site scripting attack and prevent leaking infrastructure info
=> issue#34-added helmet to prevent Cross site scripting attack 

app/components/data-components/index.js, app/components/data-components/merge-children/index.js, app/components/data-components/merge-children/merge-latest-socialpreview-into-parent.js, app/components/data-components/merge-children/merge-participants-into-parent.js, app/server/routes/server-react-render.jsx, iota.json, public.json
a new data-component called MergeChildren will find all the child itoas of a parent, and then merge the participants, and the socialpreview image.
The title meta tag will be taken from the partent iota subject.
=> merge-children for social preview, and title

app/components/web-components/undebate.jsx
This updates what's displayed to someone who visits a recorder link from a device/browser that we can't record from.
=> Pc or mac text on Can't Record Here

app/tools/copy-conversation.js
in app/tools for when you need to make a copy of a conversation that doesn't have validity conflicts
=> copy-conversation 

app/tools/cloudinary-upload.js
new tool. no changes to existing code.
=> created app/tools/cloudinary-uploader to upload and convert video files

doc/mongo-setup.md
Closes #227 
Created documentation for setting up Mongo Atlas with Heroku. Overall mongo atlas has created a great experience, setting up was pretty straight forward.This has been tested locally and in production, so you shouldnt come across any issues. 
Todo: 
Decide to merge with the install.md file or leave it as mongo-setup.md
=> issue#227 - instructions for setting up mongo atlas

app/components/react-camera-recorder.jsx, app/components/web-components/undebate.jsx
ReactCameraRecorder as a functional component
Does not rerecord placeholder video while reviewing unless asked
Info messages about audio tracks - to help debug the silent audio problem
opus audio codec is specified so firefox will work.  (but firefox on mac renders the wrong size video).
=> Functional camera recorder

app/server/server.js
make cache max_age configurable through env vars, lower default for ASSETS_MAX_AGE to 1day.
=> MAX_AGE from env option

app/components/donate-button.js, app/components/web-components/candidate-conversation.jsx, app/server/routes/server-react-render.jsx
Added gtag go candidate conversation button events.
=> Google tags

app/components/donate-button.js, app/components/web-components/candidate-conversation.jsx
don't crash if GOOGLE_ANALYTICS is not defined
=> gtag undefined if google analytics not in env

app/server/routes/server-react-render.jsx
the last fix to  to server-react-render left a character that got rendered as a new div, that caused scroll bars to appear.
=> one character scrollbar fix

app/components/web-components/index.js, app/components/web-components/note.jsx, app/tools/csv-change-recorder-urls-to-notes.js, app/tools/csv-delete-recorder-urls.js, app/tools/db-backup.sh, app/tools/db-restore.sh, app/tools/show-list-of-recorders.js, iota.json
db-backup and restore use --jsonArray to make it easier to read in the collections with node apps
a note component so urls can result in notes
tools for changing recorder urls to notes, deleting recorder urls, and showing recorders for a viewer
=> Pres fixup

app/components/lib/create-participant.js, app/components/web-components/undebate.jsx
=> can listen from speaking seat even when listening round is not the last

app/components/web-components/unpoll/index.js, app/tools/2021-bruce-amendment-viewer-recorder.js, app/tools/2021-bruce-referendum-viewer-recorder.js, app/tools/2021-bruce-viewer-recorder.js, iota.json, package-lock.json, package.json
New template to support UCLA Student association elections. Also fixed what-is-democracy in iota.json so it doesn't conflict with the _id that might already be in the db.
=> Bruce 2021
